### ISSUE TITLE
`search_targetpixelfile` hanging until timeout with tutorial code?

### ISSUE THREAD

**Issue by shianiawhite** [KeplerGO/lightkurve#460]
#### Problem description

When I attempt to run the first couple of lines from the homepage or tutorial page, the command seems to hang until a timeout.

#### Example

```python
import lightkurve as lk
pixels = lk.search_targetpixelfile("Kepler-10").download()  # Hangs here.
```
And after 10 minutes results in:
`astroquery.exceptions.TimeoutError: Timeout limit of 600 exceeded.`
(Full error below)

#### Environment:
lightkurve version 1.0b29
I've run this code from multiple machines (macOS and Ubuntu) from multiple network sources.

#### Full error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/lightkurve/search.py", line 394, in search_targetpixelfile
    month=month, campaign=campaign, sector=sector, limit=limit)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/lightkurve/search.py", line 560, in _search_products
    products = Observations.get_product_list(observations)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/mast/core.py", line 1356, in get_product_list_async
    return self.service_request_async(service, params)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/mast/core.py", line 843, in service_request_async
    retrieve_all=retrieveAll)
  File "/home/swhite/anaconda3/envs/kplr/lib/python3.6/site-packages/astroquery/mast/core.py", line 446, in _request
    raise TimeoutError("Timeout limit of {} exceeded.".format(self.TIMEOUT))
astroquery.exceptions.TimeoutError: Timeout limit of 600 exceeded.
```

**Comment by barentsen** [comment]
@shianiawhite Thank you for using Lightkurve!

It looks like the NASA data archive is down at the moment, i.e. the problem is not on your end.  Stay tuned. (/cc @scfleming)

**Comment by shianiawhite** [comment]
@barentsen Ah! Then I'm guessing this issue can be closed. Thank you.

**Comment by barentsen** [comment]
@shianiawhite I expect the issue will be resolved no later than tomorrow morning.  If you do continue to experience problems, please do feel free to re-open this issue! :+1:
