### ISSUE TITLE
raise ValueError('Input light curve has NaNs in `flux_err`. ')

### ISSUE THREAD

**Issue by exoplanet-hunter** [KeplerGO/lightkurve#731]
Dear all,

"Input light curve has NaNs in `flux_err` " destroy everything in Lightkurve. Even lk.lc.remove_nans() cannot handle this issue.  

When I create a script lk.lc.remove_nans_err(), which is quite similar to lk.lc.remove_nans(),  tpf_2min.flux[:, ~aper] will become incompatible with the lc_raw after some nan points are removed from lc_raw, so that lk.RegressionCorrector(raw_lc).correct(dm) does not work.

See details:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>> aper = tpf_2min.pipeline_mask
>>> raw_lc = tpf_2min.to_lightcurve()
>>> 
>>> # Make a design matrix
... dm = lk.DesignMatrix(tpf_2min.flux[:, ~aper], name='pixels').pca(5).append_constant()
>>> 
>>> # Regression Corrector Object
... reg = lk.RegressionCorrector(raw_lc)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/lightkurve/lightkurve/correctors/regressioncorrector.py", line 84, in __init__
    raise ValueError('Input light curve has NaNs in `flux_err`. '
ValueError: Input light curve has NaNs in `flux_err`. Please remove NaNs before correction (e.g. using `lc = lc.remove_nans()`).
>>>
>>> raw_lc = tpf_2min.to_lightcurve().remove_nans().remove_nans_err()
>>> dm = lk.DesignMatrix(tpf_2min.flux[:, ~aper], name='pixels').pca(5).append_constant()
>>> 
>>> # Regression Corrector Object
... reg = lk.RegressionCorrector(raw_lc)
>>> corrected_lc = reg.correct(dm)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lightkurve/lightkurve/correctors/regressioncorrector.py", line 221, in correct
    propagate_errors=propagate_errors)
  File "/home/lightkurve/lightkurve/correctors/regressioncorrector.py", line 154, in _fit_coefficients
    X = self.X.values[cadence_mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 18522 but corresponding boolean dimension is 13464


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Best wishes,
Sun

**Comment by danhey** [comment]
Hi @exoplanet-hunter, thanks for opening a PR! I can confirm that some stars have NaN flux errs when the flux is not NaN. A simple solution until I can investigate further is the following:

```python
m = np.isnan(raw_lc.flux_err) | np.isnan(raw_lc.flux)
raw_lc = raw_lc[~m]
# Regression Corrector Object
dm = lk.DesignMatrix(tpf.flux[~m][:, ~aper],
                         name='pixels').pca(5).append_constant()
```

**Comment by exo-hunter** [comment]
Thanks @danhey .   That's very helpful for me.  So sorry for my very very slowly reply.
