### ISSUE TITLE
search._search_products fails on astropy dev

### ISSUE THREAD

**Issue by dhomeier** [KeplerGO/lightkurve#802]
#### Problem description
In https://github.com/KeplerGO/lightkurve/issues/801#issuecomment-676732821 a new failure with the latest astropy-dev version popped up.

#### Example

```python
import lightkurve as lk
lc = lk.search_lightcurve("Pi Men", sector=12).download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/derek/lib/python3.8/site-packages/lightkurve/search.py", line 577, in search_lightcurve
    return _search_products(target, radius=radius, filetype="Lightcurve",
  File "/Users/derek/lib/python3.8/site-packages/lightkurve/search.py", line 727, in _search_products
    result['observation'] = None
  File "/Users/derek/lib/python3.8/site-packages/astropy/table/table.py", line 1666, in __setitem__
    self.add_column(value, name=item, copy=True)
  File "/Users/derek/lib/python3.8/site-packages/astropy/table/table.py", line 1952, in add_column
    raise ValueError('Inconsistent data column lengths')
ValueError: Inconsistent data column lengths
```

#### Expected behavior

https://github.com/KeplerGO/lightkurve/blob/f11ed6ccbeddbf4f95a616175f1f6830fff78400/lightkurve/search.py#L727
is trying to create a new column (which will default to `dtype=np.object`) to hold the `'observation'` entries of initially unspecified lengths. Similarly in
https://github.com/KeplerGO/lightkurve/blob/f11ed6ccbeddbf4f95a616175f1f6830fff78400/lightkurve/search.py#L63

This assignment of object-type columns of undefined length fails as of https://github.com/astropy/astropy/pull/10636 . If that is now intended behaviour in `astropy.table` (for performance reasons?), there are two possible solutions:

1. Explicitly create the new column with the correct length:
`result['observation'] = Table.Column(dtype='object', length=len(result))`

2. Find the maximum string length required for the entries and add a corresponding `str` column:
`result['observation'] = maxlen * ' '`

The 1st option should more or less exactly reproduce the current behaviour, except that it apparently initialises the column with `int` as opposed to `NoneType` entries.
The 2nd might actually be preferable from a performance POV, if there is a reasonable upper limit to the field length, as if would avoid using a variable-size `object` column.

EDIT: the new interface still allows a short and implicit assignment, providing solution

3. Pass a sequence as input:
`result['observation'] = [None]`

#### Environment

-  platform OSX 10.12
-  lightkurve version 2.0a2.dev
-  astropy version 4.2.dev504 and later
-  installation method source

**Comment by barentsen** [comment]
@dhomeier  Thanks so much for posting this excellent and detailed issue!

I am able to reproduce this bug after updating astropy.  Our existing unit tests trip over this problem:

```bash
$ pytest lightkurve/tests/test_search.py --remote-data
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/gb/dev/lightkurve, inifile: setup.cfg
plugins: forked-1.1.3, astropy-header-0.1.2, doctestplus-0.7.0, xdist-1.32.0, hypothesis-5.16.1, openfiles-0.5.0, arraydiff-0.2, remotedata-0.3.2, repeat-0.8.0
collected 18 items                                                             

lightkurve/tests/test_search.py F

=================================== FAILURES ===================================
_________________________ test_search_targetpixelfile __________________________

    @pytest.mark.remote_data
    def test_search_targetpixelfile():
        # EPIC 210634047 was observed twice in long cadence
>       assert(len(search_targetpixelfile('EPIC 210634047', mission='K2').table) == 2)

lightkurve/tests/test_search.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lightkurve/search.py:471: in search_targetpixelfile
    return _search_products(target, radius=radius, filetype="Target Pixel",
lightkurve/search.py:727: in _search_products
    result['observation'] = None
../astropy/astropy/table/table.py:1666: in __setitem__
    self.add_column(value, name=item, copy=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Table length=6>
dataproduct_type calib_level obs_collection ... dataRights_products author
     str10          int64 ...           K2 ...              PUBLIC     K2
      timeseries           2             K2 ...              PUBLIC     K2
col = <Column name='observation' dtype='float64' length=0>
, index = None
name = 'observation', rename_duplicate = False, copy = True
default_name = 'col52'

    def add_column(self, col, index=None, name=None, rename_duplicate=False, copy=True,
                   default_name=None):
        """
        Add a new column to the table using ``col`` as input.  If ``index``
        is supplied then insert column before ``index`` position
        in the list of columns, otherwise append column to the end
        of the list.
    
        The ``col`` input can be any data object which is acceptable as a
        `~astropy.table.Table` column object or can be converted.  This includes
        mixin columns and scalar or length=1 objects which get broadcast to match
        the table length.
    
        To add several columns at once use ``add_columns()`` or simply call
        ``add_column()`` for each one.  There is very little performance difference
        in the two approaches.
    
        Parameters
        ----------
        col : object
            Data object for the new column
        index : int or `None`
            Insert column before this position or at end (default).
        name : str
            Column name
        rename_duplicate : bool
            Uniquify column name if it already exist. Default is False.
        copy : bool
            Make a copy of the new column. Default is True.
        default_name : str or `None`
            Name to use if both ``name`` and ``col.info.name`` are not available.
            Defaults to ``col{number_of_columns}``.
    
        Examples
        --------
        Create a table with two columns 'a' and 'b', then create a third column 'c'
        and append it to the end of the table::
    
            >>> t = Table([[1, 2], [0.1, 0.2]], names=('a', 'b'))
            >>> col_c = Column(name='c', data=['x', 'y'])
            >>> t.add_column(col_c)
            >>> print(t)
             a   b   c
            --- --- ---
              1 0.1   x
              2 0.2   y
    
        Add column 'd' at position 1. Note that the column is inserted
        before the given index::
    
            >>> t.add_column(['a', 'b'], name='d', index=1)
            >>> print(t)
             a   d   b   c
            --- --- --- ---
              1   a 0.1   x
              2   b 0.2   y
    
        Add second column named 'b' with rename_duplicate::
    
            >>> t = Table([[1, 2], [0.1, 0.2]], names=('a', 'b'))
            >>> t.add_column(1.1, name='b', rename_duplicate=True)
            >>> print(t)
             a   b  b_1
            --- --- ---
              1 0.1 1.1
              2 0.2 1.1
    
        Add an unnamed column or mixin object in the table using a default name
        or by specifying an explicit name with ``name``. Name can also be overridden::
    
            >>> t = Table([[1, 2], [0.1, 0.2]], names=('a', 'b'))
            >>> t.add_column(['a', 'b'])
            >>> t.add_column(col_c, name='d')
            >>> print(t)
             a   b  col2  d
            --- --- ---- ---
              1 0.1    a   x
              2 0.2    b   y
        """
        if default_name is None:
            default_name = 'col{}'.format(len(self.columns))
    
        # Convert col data to acceptable object for insertion into self.columns.
        # Note that along with the lines above and below, this allows broadcasting
        # of scalars to the correct shape for adding to table.
        col = self._convert_data_to_col(col, name=name, copy=copy,
                                        default_name=default_name)
    
        # Make col data shape correct for scalars.  The second test is to allow
        # broadcasting an N-d element to a column, e.g. t['new'] = [[1, 2]].
        if (col.shape == () or col.shape[0] == 1) and len(self) > 0:
            new_shape = (len(self),) + getattr(col, 'shape', ())[1:]
            if isinstance(col, np.ndarray):
                col = np.broadcast_to(col, shape=new_shape,
                                      subok=True)
            elif isinstance(col, ShapedLikeNDArray):
                col = col._apply(np.broadcast_to, shape=new_shape,
                                 subok=True)
    
            # broadcast_to() results in a read-only array.  Apparently it only changes
            # the view to look like the broadcasted array.  So copy.
            col = col_copy(col)
    
        name = col.info.name
    
        # Ensure that new column is the right length
        if len(self.columns) > 0 and len(col) != len(self):
>           raise ValueError('Inconsistent data column lengths')
E           ValueError: Inconsistent data column lengths

../astropy/astropy/table/table.py:1952: ValueError
=========================== short test summary info ============================
FAILED lightkurve/tests/test_search.py::test_search_targetpixelfile - ValueEr...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 1 failed in 2.00s ===============================
```

My guess is that this change in behavior in AstroPy is probably not intended, so I left a comment on https://github.com/astropy/astropy/pull/10636 to check.

**Comment by barentsen** [comment]
Thanks @dhomeier! :+1:

**Comment by dhomeier** [comment]
Thanks @taldcroft for the quick upstream fix!
