### ISSUE TITLE
Lightcurve2 inconsistent behavior in replacing a column

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#866]
#### Problem description

When updating / replacing a a column, the behavior is different depending whether the replacement is done via column interface (`lc['flux'] = ...`) or attribute interface (`lc.flux = ...`)

|  Input type | Column interface | Attribute interface | `TimeSeries` |
| --- | --- | --- | --- |
|  `Quantity` | `Quantity` | `Quantity` | `Quantity` |
|  `list` | `Column` | `AttributeError` | `Column` |
|  `ndarray` | `Column` | `Quantity` | `Column` |

---

**Proposal:** piggyback on base `TimeSeries` behavior. If we do want to enforce additional behavior, it should be done for both attribute and column interfaces.

#### Example

```python
>>> import lightkurve as lk
>>> from astropy import units as u
>>> import numpy as np
>>>
>>> u_e_s = u.electron / u.second
>>> lc = lk.LightCurve(time=[1, 2, 3], flux=[0.98, 1.02, 1.03] * u_e_s)
>>>
>>>
>>> # replacing existing column using column interface
>>> lc['flux'] = np.array([1., 2., 3.])  # same as TimeSeries: a unitless Column object
>>> print(type(lc['flux']),  ' unit: ', lc['flux'].unit)
<class 'astropy.table.column.Column'>  unit:  None
>>>
>>> # replacing existing column using attribute interface
>>> lc.flux = np.array([1., 2., 3.])  # different from TimeSeries: a Quantity object with no unit
>>> print(type(lc['flux']),  ' unit: ', lc['flux'].unit)
<class 'astropy.units.quantity.Quantity'>  unit:
>>>
>>> lc['flux'] = [1., 2., 3.]   # same as TimeSeries: a unitless Column object
>>> print(type(lc['flux']),  ' unit: ', lc['flux'].unit)
<class 'astropy.table.column.Column'>  unit:  None
>>>
>>> lc.flux = [1., 2., 3.]   # different from TimeSeries: an error is raised. TimeSeries will accept it as a unitless Column object
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\lightkurve\lightkurve\lightcurve.py", line 267, in __setattr__
    value = Quantity(value, dtype=value.dtype)
AttributeError: 'list' object has no attribute 'dtype'
>>>```

#### Environment

-  lightkurve version (e.g. 1.0b6): `master`, lightkurve2.0b2 based

**Comment by barentsen** [comment]
I wrote a few thoughts on this issue over here: https://github.com/KeplerGO/lightkurve/pull/871#issuecomment-706576011

(I guess we'll continue the conversation over there.)
