### ISSUE TITLE
Not being able to use os.listdir with Tesslightcurvefile

### ISSUE THREAD

**Issue by Jadonthedankguy** [KeplerGO/lightkurve#870]
I'm currently trying to make a script that iterates through a directory to find dips in lightcurves to see if there are any potential exoplanets there.

#### Problem description

I've attempted to do this with a for loop with os.listdir, but whenever I use the directory and the file in the for loop, it thinks it's not a TESS light curve file, which is the type of file I'm trying to use, even though I downloaded the bulk download for sector 1 of tess data.

#### Example

```python
directory = 'C:/Users/Jadon Chenard/Documents/GitHub/Exoplanet-Finder/TessLightCurvesSec1/'
dipcount = 0
goodcandidates = []

print("Exo Planet Finder 9000 Starting Up...")

print("Exo Planet Started!")
f = open("log.txt", "w+")
f.write("Searching through Light Curve Files for Dips...\n")
for entry in os.listdir(directory):
    if entry.endswith(".fits"):
        lightcurve = TessLightCurveFile(directory + entry)
        pdc = lightcurve.PDCSAP_FLUX
        for fluxes in pdc.flux:
            if(fluxes < 0.95):
                dipcount+=1
                f.write("Dip Count For "+ entry + ": " + str(dipcount) + "\n")
                if dipcount >= 2:
                    print(entry + " is a good candidate!\n")
                    goodcandidates.append(os.path.join(directory, entry))
                    f.write(entry + " is a good candidate!\n")
                    dipcount = 0
                    break
f.close()
```

#### Expected behavior

I expected it do iterate through all of the files and check for dips, but instead I get this error:

Traceback (most recent call last):
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\base.py", line 406, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\header.py", line 2077, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy\io\fits\_utils.pyx", line 36, in astropy.io.fits._utils.parse_header
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Jadon Chenard/Documents/GitHub/Exoplanet-Finder/exoplanetfinder9000.py", line 17, in <module>
    lightcurve = TessLightCurveFile(directory + entry)
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\lightkurve\lightcurvefile.py", line 466, in __init__
    super(TessLightCurveFile, self).__init__(path, **kwargs)
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\lightkurve\lightcurvefile.py", line 41, in __init__
    self.hdu = pyfits.open(self.path, **kwargs)
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 164, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 403, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 1079, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 1154, in _read_next_hdu     
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\base.py", line 325, in readfrom
    hdu = cls._readfrom_internal(fileobj, checksum=checksum,
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\hdu\base.py", line 413, in _readfrom_internal     
    header = Header.fromfile(data,
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\header.py", line 513, in fromfile
    return cls._from_blocks(block_iter, is_binary, sep, endcard,
  File "C:\Users\Jadon Chenard\AppData\Local\Programs\Python\Python38\lib\site-packages\astropy\io\fits\header.py", line 596, in _from_blocks
    raise OSError('Header missing END card.')
OSError: Header missing END card.

#### Environment

-  platform (e.g. Linux, OSX, Windows):

Windows 10

-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):
I installed lightkurve via pip.

**Comment by barentsen** [comment]
@Jadonthedankguy I'm sorry to hear you are experiencing this error!

The most important error message is located at the end of the big stack trace:
```OSError: Header missing END card```

This error is usually raised when the file being opened is either not a FITS file, or is a corrupt fits file.

My recommendation is to try and figure out which file was being opened at the time the error was raised, e.g. by adding `print(directory + entry)` in the for loop.  You can then try re-downloading that file.

**Comment by barentsen** [comment]
I'm going to close this issue because it has been inactive for 10 days, but feel free to re-open if the comment above did not resolve the problem! :+1:
