### ISSUE TITLE
lightkurve 2: tpf.interact() with ylim_func is broken

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#875]
#### Problem description
On pre-release lightkurve2. `TargetPixelFile.interact(ylim_func=...)` is broken. The issue appears to be similar to #848 (for `lc.interact_bls()`)

#### Example
Calling `tpf.interact()` for a TESS TargetPixelFile on a jupyter notebook yields the following stacktrace.

```python
ylim_func = lambda lc: (np.nanpercentile(lc.flux, 0.1), np.nanpercentile(lc.flux, 99.9))
tpf.interact(ylim_func=ylim_func)
```

It yields the following error:

``` python
ERROR:tornado.application:Uncaught exception GET ...
Traceback (most recent call last):
  File "C:\pkg\_winNonPortables\Anaconda3\envs\base_dev2\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result  
...
  File "c:\dev\lightkurve\lightkurve\interact.py", line 584, in create_interact_ui
    ylim_func=ylim_func)
  File "c:\dev\lightkurve\lightkurve\interact.py", line 184, in make_lightcurve_figure_elements
    fig.y_range = Range1d(start=ylims[0], end=ylims[1])
...
  File "C:\pkg\_winNonPortables\Anaconda3\envs\base_dev2\lib\site-packages\bokeh\core\property\either.py", line 109, in validate
    raise ValueError(msg)
ValueError: expected an element of either Float, Datetime or TimeDelta, got <Quantity 6487.26757715 electron / s>
```

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows.
-  lightkurve version (e.g. 1.0b6): `master`, based on `2.0b3`
-  bokeh version: tried it with 2.2.1 and 1.2.0
-  installation method (e.g. pip, conda, source): source

**Comment by barentsen** [comment]
Thanks for catching this @orionlee! 🙏 

The interact tools unfortunately don't have great test coverage.
