### ISSUE TITLE
regressioncorrector issue with dm.pca

### ISSUE THREAD

**Issue by Mark-citizenscientist** [KeplerGO/lightkurve#880]
Hi Geert,

I am trying the regressioncorrector example from this tutorial and get the following error at dm.pca(5) using python 3.8.5, lightkurve 1.11.3, and scipy-1.5.2 on a Windows platform.  Any ideas?  Thanks, Mark

https://docs.lightkurve.org/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.html

dm = lk.DesignMatrix(regressors, name='regressors')
dm = dm.pca(5) # abends here

Traceback (most recent call last):
  File "corrector.py", line 28, in <module>
    dm = dm.pca(5)
  File "...\Local\Programs\Python\Python38\lib\site-packages\lightkurve\correctors\designmatrix.py", line 215, in pca
    new_values, _, _ = pca(self.values, nterms, n_iter=10)
  File "...\Local\Programs\Python\Python38\lib\site-packages\fbpca.py", line 1699, in pca
    (R, s, Va) = svd(QA, full_matrices=False)
  File "...\Local\Programs\Python\Python38\lib\site-packages\scipy\linalg\decomp_svd.py", line 106, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "...\Local\Programs\Python\Python38\lib\site-packages\scipy\_lib\_util.py", line 263, in _asarray_validated
    a = toarray(a)
  File "...Local\Programs\Python\Python38\lib\site-packages\numpy\lib\function_base.py", line 485, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs

**Comment by orionlee** [comment]
I have not used `DesignMatrix`. But the error seemed to indicate one of the following two problems.
1. On Windows, I encountered similar errors in calling to `.pca()` due to broken / incompatible scipy / numpy versions.
  i. I recalled python 3.8 + scipy 1.5.2 is one such broken combination (not 100% sure). The workaround is to either downgrade python to 3.7 or scipy to 1.5.0.
  ii. one way to avoid such issues it to use `conda` rather than `pip` to install the packages. In my case, `conda` caught incompatible versions and selected the working ones while `pip` will install the broken / incompatible version.

2. (Less likely) possibility that the input contains `NaN`. Maybe `regressors` cannot contain `NaN`?
  i. if so, you might need to filter out cadences where flux contains `NaN`

**Comment by Mark-citizenscientist** [comment]
Hi Sam,

Thanks for the ideas, but I tried this again with scipy 1.5.3, 1.5.2,
1.5.1, 1.5.0, 1.4.1, 1.4.0 (and 1.4.0.rc2, 1.4.0.rc1), 1.3.3, 1.3.2 and got
the same error.

I also ran the LK remove nans method before calling DM with raw_lc =
raw_lc.remove_nans() and still got this error.  I even scanned the dm
object returned by dm = lk.DesignMatrix(regressors, name='regressors')
before the line that causes this problem dm = dm.pca(5), but didn't see any
'nans' that needed fixed.  If you get any more ideas, please let me know.
Thanks, Mark

**Comment by orionlee** [comment]
1. I'd suggest you try a fresh conda python 3.7 environment and see if it works.

2. Calling `raw_lc.remove_nans()` would not help. As I understand it, the `regressor` comes from `tpf.flux`. So if having `NaN` is an issue, what it's `tpf.flux` that needs to be filtered.
(Again, I am not familiar  with the DesignMatrax api so I don't know if regressor has `NaN` will an issue or not.)

**Comment by orionlee** [comment]
Another thing you can try to see if it's a Windows-only problem is to run the codes on other platforms, e.g., you can try to run your jupyter notebook on https://colab.research.google.com/ , effectively running the codes on linux.

**Comment by Mark-citizenscientist** [comment]
Hi Sam,

Well, your Conda suggestion sounds like a lot of work but I will consider
trying that and your other test environment idea if you could try something
that would take a lot less time.  Please try running the Lightkurve
DesignMatrix example script I mentioned on your configuration and tell me
if it works for you.  Thanks, Mark

**Comment by orionlee** [comment]
1. A new conda environment should be fairly straightforward, provided you have been using Anaconda. It should be 2-3 steps (it might take a while for it to download the packages, but one does not need to keep watching it).

2. I might be able to run the example script. But I'll need your complete script.

**Comment by Mark-citizenscientist** [comment]
Hi Sam,

Well, I installed the current Anaconda Individual Edition (python 3.8.3),
and then ran 'conda install python=3.7'  as you suggested (where 3.7.7 was
installed).  And while testing in the Conda environment, I still get the
same error in both Conda python versions.  I include my DM example here for
you to try also.  Note the first TESS target in my example script plots ok
with the problem line 'dm = dm.pca(5)' commented out, but the other example
target does not. So we can't just leave this line out and still need this
fixed somehow.  Thanks, Mark

#
https://docs.lightkurve.org/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.html

import matplotlib.pyplot as plt
import lightkurve as lk
import numpy as np

target_id = "TIC 402026209"  # WASP-4b # (note this lc looks good with 'dm
= dm.pca(5)' commented out)
sector_id = 28

#target_id = "TIC 452808876" # WASP-82b # (but this does not look good with
'dm = dm.pca(5)' commented out; the corrected_lc looks flat)
#sector_id = 5

search_result = lk.search_tesscut(target_id, sector=sector_id)
tpf = search_result.download(cutout_size=10,quality_bitmask='default')

aper = tpf.create_threshold_mask()
raw_lc = tpf.to_lightcurve(aperture_mask=aper)

raw_lc = raw_lc.remove_nans()

regressors = tpf.flux[:, ~aper]

dm = lk.DesignMatrix(regressors, name='regressors')

### comment this line out to get plots, but note the error mentioned above
dm = dm.pca(5)
###

dm = dm.append_constant()

corrector = lk.RegressionCorrector(raw_lc)
corrector.correct(dm)

model = corrector.model_lc
#model.plot()

model -= np.percentile(model.flux, 5)

corrected_lc = raw_lc - model

ax = raw_lc.plot(label='Raw light curve')
corrected_lc.plot(ax=ax, label='Corrected light curve');

bkg = np.median(regressors, axis=1)
bkg -= np.percentile(bkg, 5)

npix = aper.sum()
median_subtracted_lc = raw_lc - npix * bkg

ax = median_subtracted_lc.plot(label='Median background subtraction')
corrected_lc.plot(ax=ax, label='RegressionCorrector');

plt.show()

**Comment by orionlee** [comment]
Hmm, I tried the 2 target-sector pairs (`"TIC 402026209", 28  ; "TIC 402026209", 5`). They worked (i.e., `dm.pca(5)` does not cause error) on my (Windows 10) machine.

1. You could try it on google colab https://colab.research.google.com/github/KeplerGO/lightkurve/blob/master/docs/source/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.ipynb

Insert a new cell before `import lightkurve` with the following so that it would install `lightkurve` on the hosting machine:
```python
if 'google.colab' in str(get_ipython()):
    !pip install lightkurve
```

2. On my machine, I use the following packages. 

![image](https://user-images.githubusercontent.com/250644/97053671-37981e00-1538-11eb-8df8-bf286b0c6fac.png)

In case it makes a difference, I used `conda-forge` channel for all of my installation.

**Comment by Mark-citizenscientist** [comment]
Hi Sam,

Thanks for trying my Lightkurve DM example.  With another try here, I
finally got past "dm = dm.pca(5)" and got my two example target plots
working in both Anaconda 3.7.7 and the current version 3.8.3.  (I ran conda
install python=3.8 to see if this would work too, and it did.)  So it seems
that something in my regular python 3.8.5 install was causing this problem
and using Anaconda's python is the solution as you first suggested.  Thanks
again for all your ideas!  Mark

p.s. Geert, you rock and Lightkurve is super great!! :)
